version: "3.8"

services:
  mysql:
    image: mysql
    container_name: MySQL
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - "D:/Docker Volumes/MySQL_Data:/var/lib/mysql"
  redis:
    image: redis
    container_name: Redis
    ports:
      - "6379:6379"
    volumes:
      - "D:/Docker Volumes/Redis_Data:/data"
    entrypoint: [ "redis-server", "--appendonly", "yes", "--requirepass", "123456" ]
  nacos:
    image: nacos/nacos-server:v3.0.3
    container_name: Nacos
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone
      NACOS_AUTH_TOKEN: TkFDT1NfQVVUSF9UT0tFTl9XRUFSS1NZX1RPX0JBU0U2NA==
      NACOS_AUTH_IDENTITY_KEY: NACOS_AUTH_IDENTITY_KEY_WEARSKY
      NACOS_AUTH_IDENTITY_VALUE: NACOS_AUTH_IDENTITY_VALUE_WEARSKY
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: 192.168.1.200
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: 123456
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      NACOS_SERVER_IP: 192.168.1.200
    depends_on:
      - mysql
    restart: on-failure
  seata:
    image: apache/seata-server:2.5.0
    container_name: Seata
    ports:
      - "7091:7091"
      - "8091:8091"
    volumes:
      - "D:/Docker Volumes/Seata_Config:/seata-server/resources"
    environment:
      SEATA_IP: 192.168.1.200
    depends_on:
      - nacos
    restart: on-failure
  rabbitmq:
    image: rabbitmq:management
    container_name: RabbitMQ
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: wearsky
      RABBITMQ_DEFAULT_PASS: 123456
  elasticsearch:
    image: elasticsearch:8.18.8
    container_name: Elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - "D:/Docker Volumes/Elasticsearch_Data:/usr/share/elasticsearch/data"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
  sentinel:
    image: bladex/sentinel-dashboard:1.8.9
    container_name: Sentinel
    ports:
      - "8719:8719"
      - "8858:8858"
