spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        group: BLOG
      config:
        namespace: dev
        group: BLOG
  config:
    import:
      - nacos:log.yaml?refreshEnabled=true
      - nacos:knife4j.yaml?refreshEnabled=true
      - nacos:seata.yaml?refreshEnabled=true
      - nacos:rabbitmq.yaml?refreshEnabled=true
      - nacos:mybatis-plus.yaml?refreshEnabled=true
      - nacos:blog-service.yaml?refreshEnabled=true
#  application:
#    name: blog-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/blog_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: blog
#    username: blog
#    password: 123456
#    connection-timeout: 1s # 设置MQ的连接超时时间
#    template:
#      retry:
#        enabled: true # 开启超时重试机制
#        initial-interval: 1000ms # 失败后的初始等待时间
#        multiplier: 2 # 失败后下次的等待时长倍数，下次等待时长 = initial-interval * multiplier
#        max-attempts: 1 # 最大重试次数
#    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型：none、关闭 simple、同步阻塞 correlated、异步回调
#    publisher-returns: true # 开启publisher return机制
#    listener:
#      simple:
#        prefetch: 1 # 每次取一条消息，处理完后再取下一条，不平均分，能者多劳

#server:
#  port: 38080

#mybatis-plus:
#  configuration:
#    cache-enabled: false # 二级缓存
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  mapper-locations: classpath*:/mapper/*.xml

#seata:
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace: dev
#      group: BLOG
#      application: seata-server # seata服务名称
#  tx-service-group: blog
#  service:
#    vgroup-mapping:
#      blog: default # tx-service-group跟seata集群的映射关系

## springdoc-openapi项目配置
#springdoc:
#  default-flat-param-object: true # 将对象参数展开为独立的query参数
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn

#logging:
#  file:
#    name: ./log/${spring.application.name}.log
#  level:
#    com.wearsky.demo: debug