spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: blog
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/user-service/**
            - id: blog-service
              uri: lb://blog-service
              predicates:
                - Path=/blog-service/**
            - id: click-service
              uri: lb://click-service
              predicates:
                - Path=/click-service/**

server:
  port: 18080

jwt:
  public-key-path: classpath:keys/public-key.pem
