spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        group: BLOG
      config:
        namespace: dev
        group: BLOG
  config:
    import:
      - optional:nacos:sentinel.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:gateway.yaml
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: user-service
#              uri: lb://user-service
#              predicates:
#                - Path=/user-service/**
#            - id: blog-service
#              uri: lb://blog-service
#              predicates:
#                - Path=/blog-service/**
#            - id: click-service
#              uri: lb://click-service
#              predicates:
#                - Path=/click-service/**
#  application:
#    name: gateway
#  data:
#    redis:
#      host: localhost
#      port: 6379
#      password: 123456
#
#server:
#  port: 8081
#
#jwt:
#  public-key-path: classpath:keys/public-key.pem