spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        group: BLOG
      config:
        namespace: dev
        group: BLOG
  config:
    import:
      - nacos:log.yaml
      - nacos:knife4j.yaml
      - nacos:seata.yaml
      - nacos:rabbitmq.yaml?refreshEnabled=true
      - nacos:mybatis-plus.yaml
      - nacos:user-service.yaml?refreshEnabled=true
#  application:
#    name: user-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/user_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

#server:
#  port: 28080

#jwt:
#  private-key-path: classpath:keys/private-key.pem
#  expiration-ms: 3600000

#mybatis-plus:
#  configuration:
#    cache-enabled: false # 二级缓存
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  mapper-locations: classpath*:/mapper/*.xml

#seata:
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 127.0.0.1:8848
#      namespace: dev
#      group: BLOG
#      application: seata-server # seata服务名称
#  tx-service-group: blog
#  service:
#    vgroup-mapping:
#      blog: default # tx-service-group跟seata集群的映射关系

## springdoc-openapi项目配置
#springdoc:
#  default-flat-param-object: true # 将对象参数展开为独立的query参数
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn

#logging:
#  file:
#    name: ./log/${spring.application.name}.log
#  level:
#    com.wearsky.demo: debug