spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        group: BLOG
      config:
        namespace: dev
        group: BLOG
  config:
    import:
      - nacos:log.yaml?refreshEnabled=true
      - nacos:knife4j.yaml?refreshEnabled=true
      - nacos:rabbitmq.yaml?refreshEnabled=true
      - nacos:mybatis-plus.yaml?refreshEnabled=true
      - nacos:click-service.yaml?refreshEnabled=true
#  application:
#    name: click-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: xmm13622670
#    url: jdbc:mysql://localhost:3306/click_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: blog
#    username: blog
#    password: 123456
#    listener:
#      simple:
#        prefetch: 1 # 每次取一条消息，处理完后再取下一条，不平均分，能者多劳

#server:
#  port: 48080

#mybatis-plus:
#  configuration:
#    cache-enabled: false # 二级缓存
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.wearsky.demo.*.domain.entity

## springdoc-openapi项目配置
#springdoc:
#  default-flat-param-object: true # 将对象参数展开为独立的query参数
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn

#logging:
#  file:
#    name: ./log/${spring.application.name}.log
#  level:
#    com.wearsky.demo: debug