spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
        group: BLOG
      config:
        namespace: dev
        group: BLOG
  config:
    import:
      - optional:nacos:log.yaml?refreshEnabled=true
      - optional:nacos:sentinel.yaml
      - optional:nacos:knife4j.yaml?refreshEnabled=true
      - optional:nacos:rabbitmq.yaml?refreshEnabled=true
      - optional:nacos:mybatis-plus.yaml?refreshEnabled=true
      - optional:nacos:click-service.yaml?refreshEnabled=true
#  application:
#    name: click-service
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/click_service?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#  rabbitmq:
#    host: localhost
#    port: 5672
#    virtual-host: blog
#    username: blog
#    password: 123456
#    listener:
#      simple:
#        prefetch: 1 # 每次取一条消息，处理完后再取下一条，不平均分，能者多劳
#        acknowledge-mode: auto # none：不处理、manual：手动、auto：自动（如果是业务异常，会自动返回nack；如果是消息处理或校验异常，自动返回reject）
#        retry:
#          enabled: true # 开启消费者失败重试
#          initial-interval: 1000ms # 初次失败等待时长为1秒
#          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
#          max-attempts: 3 # 最大尝试次数
#          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false

#server:
#  port: 48080

#mybatis-plus:
#  configuration:
#    cache-enabled: false # 二级缓存
#    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.wearsky.demo.*.domain.entity

## springdoc-openapi项目配置
#springdoc:
#  default-flat-param-object: true # 将对象参数展开为独立的query参数
## knife4j的增强配置，不需要增强可以不配
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn

#logging:
#  file:
#    name: ./log/${spring.application.name}.log
#  level:
#    com.wearsky.demo: debug